onboarding = false
[experimental]
pane_history = false
allow_nested = true

[keys]
prefix = "ctrl+space"
previous_tab = ["prefix+p", "prefix+shift+h", "ctrl+alt+h"]
next_tab = ["prefix+n", "prefix+shift+l", "ctrl+alt+l"]

[ui.sound]
enabled = true

[ui.toast]
delivery = "off"

[theme]
name = "catppuccin"
auto_switch = false
