#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status.

# Define color variables
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting system cleanup process...${NC}"

# Clean package cache
echo -e "${YELLOW}Cleaning package cache...${NC}"
sudo nala clean

# Managing System Logs
echo -e "${YELLOW}Checking current disk usage by journal logs...${NC}"
sudo journalctl --disk-usage

echo -e "${YELLOW}Rotating journal logs...${NC}"
sudo journalctl --rotate

echo -e "${YELLOW}Cleaning up old journal logs...${NC}"
sudo journalctl --vacuum-time 1d

echo -e "${YELLOW}Checking disk usage by journal logs after cleanup...${NC}"
sudo journalctl --disk-usage

# Uncomment the following lines if you want to use them after reviewing their actions
# echo -e "${YELLOW}Trimming filesystem...${NC}"
# sudo fstrim -va

echo -e "${YELLOW}Purging residual config packages...${NC}"
sudo dpkg --purge "$(COLUMNS=200 dpkg -l | grep "^rc" | tr -s ' ' | cut -d ' ' -f 2)" 2>/dev/null

# echo -e "${YELLOW}Removing orphaned packages with deborphan...${NC}"
# sudo deborphan | xargs sudo apt-get -y remove --purge

# Clean /tmp Directory
# Caution: This will remove all files and directories in /tmp. Ensure no critical operations are using /tmp.
echo -e "${RED}Cleaning /tmp directory...${NC}"
sudo rm -rf /tmp/*

# Auto-remove unneeded packages
echo -e "${YELLOW}Removing unneeded packages...${NC}"
sudo nala autoremove -y

echo -e "${GREEN}System cleanup process completed!${NC}"

sudo powertop --auto-tune
