#!/bin/bash

# ANSI color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check the number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo -e "${RED}Usage: $0 <commit_message> [tag_name]${NC}"
    exit 1
fi

# Add changes to the staging area
if ! git add .; then
    echo -e "${RED}Error: Unable to add files to the staging area.${NC}"
    exit 1
fi

echo -e "${GREEN}Files are added to the staging area.${NC}"
echo

# Commit changes
commit_message="$1 at $(date --rfc-3339 date)"
if ! git commit -am "$commit_message"; then
    echo -e "${RED}Error: Unable to commit changes.${NC}"
    exit 1
fi

echo -e "${GREEN}Files are committed with the message: $commit_message${NC}"


if ! git push ; then 
    echo -e "${RED}Error: Unable to Push.${NC}"
    exit 1    
fi

echo -e "${GREEN}Changes pushed successfully.${NC}"


# Tagging (if two arguments provided)
if [ "$#" -eq 2 ]; then
    if git tag "$2"; then
        echo -e "${GREEN}Tag $2 created.${NC}"
        # Push the commit (already pushed above), then push the tag
        if git push --tags; then
            echo -e "${GREEN}Tag pushed successfully.${NC}"
        else
            echo -e "${RED}Error: Unable to push tag to the remote repository.${NC}"
            exit 1
        fi
    else
        echo -e "${RED}Error: Unable to create tag $2.${NC}"
        exit 1
    fi
fi

