#! /bin/bash

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

scripts_path="$HOME/.$USER-bin"
script_name="$1"
rc_file=.zshrc

echo $scripts_path

# Create the directory if it doesn't exist
if [[ ! -d "$scripts_path" ]]; then
    mkdir -p "$scripts_path"
    echo -e "${GREEN}Created directory $scripts_path${NC}"
else
    echo -e "${YELLOW}Directory $scripts_path already exists${NC}"
fi



exists=$(echo "$PATH" | tr ':' '\n' | grep "$scripts_path")
if [ -z "$exists" ]; then
    echo "export PATH=""$PATH":"$scripts_path""" >> "$HOME/$rc_file"
fi

# # Create a symbolic link
ln -f "$script_name" "$scripts_path"
if [[ $? -eq 0 ]]; then
    echo -e "${GREEN}Linked $script_name to $scripts_path${NC}"
else
    echo -e "${RED}Failed to link $script_name to $scripts_path${NC}"
fi

exec $SHELL

