#! /bin/env python3

import os
import subprocess
import requests

username = "oovaa" # github username
url = f"https://api.github.com/users/{username}/repos"
user_data = requests.get(url)
repos =user_data.json()
for repo in repos:
	print(repo['name'])
	gh_name = repo['full_name']
	os.system(f'gh repo clone {gh_name}')

